version: '3'
services:
  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - "2717:27017"
    #    environment:
    #      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
    #      - MONGO_INITDB_ROOT_PASSWORD=secret
